plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
 - npc_dota_hero_hidan
 - npc_dota_hero_kisame
 - npc_dota_hero_naruto
 - npc_dota_hero_guy
 - npc_dota_hero_kakashi
 - npc_dota_hero_anko
 - npc_dota_hero_onoki
 - npc_dota_hero_raikage
 - npc_dota_hero_sakura
 - npc_dota_hero_madara
 - npc_dota_hero_zabuza
 - npc_dota_hero_shisui
 - npc_dota_hero_yondaime
 - npc_dota_hero_itachi
 - npc_dota_hero_sasuke
 - npc_dota_hero_gaara
 - npc_dota_hero_kankuro
 - npc_dota_hero_shikamaru
 - npc_dota_hero_temari
 - npc_dota_hero_haku
 - npc_dota_hero_sai
